apiVersion: v1
kind: Pod
metadata:
  name: ngnix-image
spec:
  containers:
    - name: ngnix
      image: acrclaritycloudmgmt.azurecr.io/docker/clarity-cloud-devcontainer-base:latest
      imagePullPolicy: Always
      ports:
      - name: nginx
        containerPort: 8080
        protocol: TCP
  imagePullSecrets:
    - name: clarity-cloud-acr-cred
